### ISSUE TITLE
Ability to change the title/name of a shopping list

### ISSUE THREAD

**Issue by kft-a** [zznicole/shopping-list#11]
Currently it is not possible for the user to name a shopping list. There should be an input field to set the name.

Either allow for inline editing in ListsScreen (but that will likely interfere with a click to go to the TobuyListScreen), or on the top of TobuyListScreen.

**Comment by kft-a** [comment]
Use API call POST editlist with request data = {summary: <title>, description: <description, leave as "" for now>, done: <true or false>}

See function createList(title) in ListsScreen.js for how to make the call.

**Comment by zznicole** [comment]
thanks, I have made the title in toBuyListScreen updatable. Now will work on listsScreen.

**Comment by kft-a** [comment]
Fixed backend part of this so now it works. Commit #fd97c0711547ec on master.
