### ISSUE TITLE
The title/name of a shopping list should be shown at the top of TobuyListScreen.

### ISSUE THREAD

**Issue by kft-a** [zznicole/shopping-list#12]
Currently it is hard coded to 'Grocery List', it should show the name of the list whose items are shown.

**Comment by kft-a** [comment]
The apiBaseUrl + "getlist?listid=" + listid API call returns:
response.data.result, where result = {
      listid: req.query.listid,
      summary: list.summary,
      isOwn: <true if current user is owner>
      isShared: <true if multiple users have this list>
      items: items };

**Comment by zznicole** [comment]
The list title is editable now in toBuyListScreen, and it will update the title which is located in listsScreen and regards to the same list.
