### ISSUE TITLE
Confirmation on Delete list

### ISSUE THREAD

**Issue by kft-a** [zznicole/shopping-list#22]
When pressing the delete button on a list, there should be a confirmation question. Not needed on delete of tobuy items.

**Comment by kft-a** [comment]
An alternative is that no delete buttons are shown normally, and there is a 'master' delete at the top or somewhere, which, when pressed, make the current delete buttons visible.

**Comment by zznicole** [comment]
This issue in Listsscreen.js is solved. When the user clicks the delete icon, the confirmation options pop up, then the list is deleted when user click on ok, or the list is not deleted if user click on cancel.
