### ISSUE TITLE
Consistent title in the app bar

### ISSUE THREAD

**Issue by kft-a** [zznicole/shopping-list#38]
Should it say 'Our Shopping List' on the login, signup and verify screens, or should it show the action as in 'LOG IN' and 'SIGN UP'?

**Comment by zznicole** [comment]
This issue is connected with issue #25 _Login screen UI need to be analyse and updated_. We might not need an app bar in the login screen.

**Comment by zznicole** [comment]
the app bar issue is solved with #25 , after rewriting code  for login and signup screens
